version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gobarber
    ports:
      - '5433:5432'

  mongo:
    image: bitnami/mongodb:latest
    restart: unless-stopped
    environment:
      - MONGODB_USERNAME=gobarber
      - MONGODB_PASSWORD=
      - MONGODB_DATABASE=gobarber
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '27017:27017'

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
